### ISSUE TITLE
Break up JCL into individual JAR files

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio_jcl#1]
Currently, DoppioJVM issues a network request for every individual uncompressed class file it needs to load. This is awful when you are not on a fast connection.

It would be much better to package the JCL into multiple jar files, perhaps through subdividing the packages. I will need to do an experiment to see what packages are touched by which programs, to see if there's a sensible separation that can minimize network time.
- [ ] Enumerate GUI-related packages (e.g. *.awt.* and *.swing.*), and segment off to a separate JAR file.
- [x] Avoid integrating `ecj`'s source into `java_home`. There's no need for that anymore, now that Doppio has built-in JAR file support.
- [ ] Experiment to determine other useful segmentations.

**Comment by jvilk** [comment]
It looks like `lib/meta-index` is responsible for mapping resources to JAR files. `sun.misc.MetaIndex` reads it, and describes its use. We should appropriately generate this when we create the JAR files.

**Comment by jvilk** [comment]
We should also endeavor to appropriately split metadata, too.

**Comment by jvilk** [comment]
I want to note that doing this will make it feasible to completely remove our tar loading hack in our demo.

I used Disk Inventory X on my Mac to quantify the size of each package inside `rt.jar` (there are other JAR files we extract from `java_home`, but they are <3MB and will be much smaller if we re-zip them in storage mode and gzip them to take advantage of solid compression (think of all the shared strings in the constant pools)).

Here are the packages (**extracted** size). I will **bold** items I suspect can be broken out into a sub-JAR, once I study package usage in our demo apps:
- com (25.7MB)
  - sun (25.6MB)
    - **org (9.8MB)**
      - apache / glassfish / omg
    - **xml (7.8MB)**
    - **corba (2.7MB)**
    - java (1.7MB)
      - **swing (1.1MB)**
      - ...
    - **media (<1MB)**
      - sound (the only subpackage)
    - ...
  - oracle (149kB)
- sun (12.5MB)
  - **awt (3.0MB)**
  - security (2.9MB) (can probably prune subpackages here if desired)
  - nio (<1MB)
  - **java2d (<1MB)**
- java (9.4MB)
  - util (3.4MB)
  - **awt (1.7MB)**
  - **lang (1.2MB)**
  - ...
- javax (8.9MB)
  - **swing (6.1MB)**
  - **management (<1MB)** (seems to be swing-related?)
  - **xml (<1MB)**
  - ...
- org (1.2MB)
  - **omg (<1MB)**
  - ...
- **jdk (620kB)** (unknown what these packages are used for -- perhaps JDK tools?)

Right now, it looks like we have the possibility of:
- Breaking out media/graphics/etc into a `GUI.jar`.
- Breaking out XML/CORBA/etc stuff into `SerializationFormats.jar`?
- Breaking out other stuff into an `Uncommon.jar`?

**Comment by jvilk** [comment]
As a side note, the JDK "cheats" a bit and actually has a preprocessed `classlist` file listing every single class file in `rt.jar`.

We can produce a `classlist.json` for our JAR files, letting us put all of the JAR files onto the classpath but preventing the scenario where the bootstrap classloader pulls in every single JAR file the first time it cannot find a class file. Meaning, our bootstrap classloader has ahead-of-time knowledge of every class it will ever potentially load.

**Comment by perimosocordiae** [comment]
+1 for a classlist file.

**Comment by jvilk** [comment]
Let's just use the stuff already in there.
